### ISSUE TITLE
B2- Mana Pick-Up & B4- Weapon issue

### ISSUE THREAD

**Issue by eabenoit01** [RinglingGameArt/2020_Soph_AdventureGame#10]
1) If I spam the weapon and try to walk at the same time, the weapon stops moving. But I was really spamming it. Like really hard. 
2) Some Mana doesn't pick up even though I'm low on Mana or out of it. I had this issue with a few BP, it was a "Do-Once" before a "Cast to BP". Just put the "Do-Once" right after the "Cast To". You might have this but Eric said it would break any BP. Hope this helps! Also love the music!
3) Also I might just be stupid but I cant get through the final door even though I grabbed the huge snowflake. Again, it might just be 100% user issue!

**Comment by apatters1** [comment]
Added a delay between the weapon's deployment and reset, seems to have fixed this issue as one can no longer spam weapon continuously. Fixed mana pick up issue by making the false branch that determines if there's less than three mana to keep running as it was previously being read as do once.

Have plans to implement dialogue moment  once BP is up and running on ice boost to make it clear to player, print string is not enough.
