### ISSUE TITLE
B1- Weapon Animation feels Long and Odd to use sometimes

### ISSUE THREAD

**Issue by AndresTVidal** [RinglingGameArt/2020_Soph_AdventureGame#1019]
Weapon animation feels odd, it's hard to tell what the animation is trying to do. I thinking having a more clear and obvious build-up and deployment of the attack will help a lot. Increasing the range of the hitbox by about 20-25% percent forward might make the range feel better. Animation should be around .8 seconds or maybe shorter, it feels like I'm stuck in the animation for a while. When moving up or down movement is disabled while moving left or right isn't while attacking.

**Comment by sbeauchaa** [comment]
Changed the way the weapon displays sound and animation and also fixed the movement blueprint was causing the character to only be disabled while moving up and down. It now stops movement in all directions while using the weapon.
