### ISSUE TITLE
C1- Sound when Hit are Somewhat Varied for the Character

### ISSUE THREAD

**Issue by AndresTVidal** [RinglingGameArt/2020_Soph_AdventureGame#1020]
The pitch of the sound when hurt can differ to a noticeable degree due to the pitch of the voices. Equalizing the sounds through filters or removing some of the ones that differ too much from the intended voice might work.

**Comment by sbeauchaa** [comment]
Changed the range that the pitch would change to significantly smaller. The voice response should be much more consistent now.
