### ISSUE TITLE
A4- Camera can Glitch Out while Transitioning 

### ISSUE THREAD

**Issue by AndresTVidal** [RinglingGameArt/2020_Soph_AdventureGame#1035]
During some camera transitions the camera will go back to the original room you moved from. Happens randomly, mostly when going up to a new room. Not sure why this happens, it's very inconsistent of when it occurs.

**Comment by sbeauchaa** [comment]
It was caused by trigger boxes being just close enough for it get stuck between switching the camera for the two rooms making the camera rapidly switch. Solved by moving them further apart.
