### ISSUE TITLE
A1- Stuck on gates

### ISSUE THREAD

**Issue by ccorker** [RinglingGameArt/2020_Soph_AdventureGame#113]
![jessica](https://user-images.githubusercontent.com/55284909/75997511-6ee48c80-5ecd-11ea-8786-9db30063ed2b.JPG)
![Jessica2](https://user-images.githubusercontent.com/55284909/75997512-6f7d2300-5ecd-11ea-8d24-df64190de9f1.JPG)

You get stuck on the gates and can't get out of it. If you are standing in the direction of where the gate swings open it just pushes you into the corner and keeps you there. This probably has to do with its collision.

**Comment by jblank123** [comment]
gate now opens the other way, fixed
