### ISSUE TITLE
Feedback Notes 4/23 for Charlotte

### ISSUE THREAD

**Issue by scarrollrcad** [RinglingGameArt/2020_Soph_AdventureGame#1188]
Say Nodes needs a DoOnce

Rework room 09 and room 08

![image](https://user-images.githubusercontent.com/6991620/80107868-a2e14300-8549-11ea-9cf6-3fe5e531032e.png)

Boss Reveal - Story Outro
Have door slowly open.  Boss reveals self.
Low camera angle makes subjects feel more imposing.
Dialogue

**Comment by scarrollrcad** [comment]
Ranged Enemies - Damage amount seems fine but consider speeding up the reload time for your Ranged Enemies.  Its too easy to outrun your ranged enemies.  Consider tuning projectile speed as well.

**Comment by ccorker** [comment]
also clean up in-game dialogue prompts: 
-use correct sound(s)
-make sure there are no extra message boxes
-add a do once to the BP
