### ISSUE TITLE
B1: Any room: Weapon offset

### ISSUE THREAD

**Issue by sbeauchaa** [RinglingGameArt/2020_Soph_AdventureGame#12]
When hitting both attacks at once the weapon gets offset from the player and floats in space making it difficult to attack. 
 
Expectation: Weapon wont offset when you attack with both parts of the weapon at the same time.

**Comment by apatters1** [comment]
Tested after adding a delay for how often the player can deploy the weapon, could not replicate this bug, seems to be fixed
