### ISSUE TITLE
B2- Patrolling Haz moving through walls & B1- Weapon animation 

### ISSUE THREAD

**Issue by eabenoit01** [RinglingGameArt/2020_Soph_AdventureGame#136]
1) two of your patrolling enemies go through the walls 

![Screenshot (43)](https://user-images.githubusercontent.com/55291838/75998902-8290f280-5ecf-11ea-9b35-07ed09843aa0.png)

![Screenshot (45)](https://user-images.githubusercontent.com/55291838/75998937-8de41e00-5ecf-11ea-9365-1f4ba06633fd.png)

2) Weapon still is too slow, love the build up but it needs to be faster. this makes killing enemies too long! 
3) love your sound effects!

**Comment by sbeauchaa** [comment]
Changed the placement of the patrolling enemies, they now do not clip through the walls. Made the weapon hit quicker as well.
