### ISSUE TITLE
B1: Ranged enemies shoot too fast 

### ISSUE THREAD

**Issue by apatters1** [RinglingGameArt/2020_Soph_AdventureGame#139]
The delay between each shot the ranged enemy takes is too short to get even one hit in with the current weapon speed. Not enough time to make them fire then hide and be able to run past them. Projectile speed also needs to be slowed on top of this

Add a longer delay between firing, and maybe continue working on weapon, it still feels too slow

**Comment by sbeauchaa** [comment]
Slowed the speed of the range enemies attacks and added cues for when the range enemies will shoot. Worked on weapon and sped it up.
