### ISSUE TITLE
A1: Room5: 1. The control fangx after the resurrection is wrong; 2. It will be damaged after the resurrection 3. It will be stuck by the enemy and cannot pass.

### ISSUE THREAD

**Issue by yzhang210** [RinglingGameArt/2020_Soph_AdventureGame#14]
![UE4Game 2020-03-05 09-34-46-67](https://user-images.githubusercontent.com/55291906/75991780-fb3e8180-5ec4-11ea-8b18-af1cc8ef34b5.jpg)
![UE4Game 2020-03-05 09-34-47-84](https://user-images.githubusercontent.com/55291906/75991782-fbd71800-5ec4-11ea-9fa2-62a16cceb3e4.jpg)
![UE4Game 2020-03-05 09-34-51-39](https://user-images.githubusercontent.com/55291906/75991783-fbd71800-5ec4-11ea-9dbe-934ef3188e41.jpg)
![UE4Game 2020-03-05 09-35-00-98](https://user-images.githubusercontent.com/55291906/75991786-fbd71800-5ec4-11ea-88e1-173a41650dd2.jpg)
![UE4Game 2020-03-05 09-35-07-68](https://user-images.githubusercontent.com/55291906/75991787-fbd71800-5ec4-11ea-9253-971cdf4b9ea9.jpg)

**Comment by apatters1** [comment]
Updated and fixed rotation of checkpoint spawns
