### ISSUE TITLE
S: Ranged's shooting a little bit fast

### ISSUE THREAD

**Issue by yzhang210** [RinglingGameArt/2020_Soph_AdventureGame#142]
![UE4Game 2020-03-05 10-57-58-94](https://user-images.githubusercontent.com/55291906/75999606-79ecec00-5ed0-11ea-901d-1a1ed4491e4a.jpg)
![UE4Game 2020-03-05 10-58-00-86](https://user-images.githubusercontent.com/55291906/75999607-79ecec00-5ed0-11ea-9cc5-75d3dee8b357.jpg)

**Comment by sbeauchaa** [comment]
Slowed down the shooting of the ranged enemies and added a buildup sound before they shoot

**Comment by sbeauchaa** [comment]
Slowed down the shooting, added a build up sound and added a flash of material for when you are within shooting range.
