### ISSUE TITLE
B1: Moving Trap and Ranged too Fast

### ISSUE THREAD

**Issue by AndresTVidal** [RinglingGameArt/2020_Soph_AdventureGame#145]
Ranged: The rate of fire and the velocity are too fast, especially with the current player speed.
Moving Trap: They clip into the ground and attack the player too quickly. They also retract too quickly.

**Comment by sbeauchaa** [comment]
Slowed down the shooting of the ranged enemies and added sound and flashing before they shoot. Trap should no longer clip into the ground they were also slowed.
