### ISSUE TITLE
A1: Can't get through gate

### ISSUE THREAD

**Issue by apatters1** [RinglingGameArt/2020_Soph_AdventureGame#147]
Picked up the key, and died. Then respawned at the checkpoint that has the 'get away' gate and can't get through it.

Would like to be able to get through the gate or keep the key upon death since now the key doesn't exist anymore in game to go repick it up.

**Comment by sbeauchaa** [comment]
Double checked key blueprint to make sure that you can save it and do not lose it after you die. Can now get through gate when you die
