### ISSUE TITLE
B2: Enemy Hit boxes seem to be Off

### ISSUE THREAD

**Issue by AndresTVidal** [RinglingGameArt/2020_Soph_AdventureGame#15]
When walking into static enemies, some angles won't hurt the player at all. Whith patrolling enemies, sometimes the patrol enemies won't do damage if you stand still in their path. Only works in certain directions. Sometimes knockback works, sometimes it doesn't.

**Comment by apatters1** [comment]
Updated static enemy collision. Updated patrolling enemy collision as well, but was unable to replicate the issue of no damage being taken while standing still in their path. There is a delay between hits as to not stack damage, shortened delay from 3 seconds to 2 seconds
