### ISSUE TITLE
B: one moving trap moving strangely

### ISSUE THREAD

**Issue by ewoods505** [RinglingGameArt/2020_Soph_AdventureGame#152]
I know this was mentioned in class but there is still that one area of moving traps, where the traps don't move on the plates. I don't know how to fix that but it messes with those specific traps functionality. 
![sam](https://user-images.githubusercontent.com/55291558/76000124-3cd52980-5ed1-11ea-8177-2542d96378d8.PNG)

**Comment by sbeauchaa** [comment]
Changed the trigger for the traps as well as the location of the traps. They are now functioning correctly.
