### ISSUE TITLE
1C: First enemy

### ISSUE THREAD

**Issue by ewoods505** [RinglingGameArt/2020_Soph_AdventureGame#16]
weird glitch I was able to repeat every time. if the player character walks directly to the wolf static enemies nose (works with the first at the gate) the damage won't happen immediately. the damage won't react till you try and move again. and then after moving again the damage and hit back happens.

![apatters](https://user-images.githubusercontent.com/55291558/75991828-0beef780-5ec5-11ea-8ee5-38b618b4decc.PNG)

**Comment by apatters1** [comment]
Changed collision on all enemies to be capsule which allows ice projectile to hit everytime as well as damage player accurately 100%
