### ISSUE TITLE
B1: Room 9- Final Door Opens with Regular Projectile

### ISSUE THREAD

**Issue by AndresTVidal** [RinglingGameArt/2020_Soph_AdventureGame#20]
Once you pick up the necessary power-up for the last door, it is not necessary to charge in order to open. Not sure if this is a bug or if this could be useful for the player? However, I think it should work as intended but overall, not game breaking, just can happen often.

**Comment by apatters1** [comment]
Couldn't replicate the door being broken with a regular projectile, but did find that the heavy projectile could be fired before charge animation was done. I have fixed the timing by shortening the timeline of the animation and adding a delay
