### ISSUE TITLE
B1: Sword range appears limited

### ISSUE THREAD

**Issue by scarrollrcad** [RinglingGameArt/2020_Soph_AdventureGame#44]
Start with the sword up in the idle.  Have it extend far in front of the player when the player presses the primary action button.

The NES Zelda 'poke attack' is a great example.

![image](https://user-images.githubusercontent.com/6991620/75993342-53768300-5ec7-11ea-92ee-dbc18bca5425.png)

**Comment by ccorker** [comment]
adjusted weapon and range
