### ISSUE TITLE
A1: Room 2: Sometimes I can't cause damage to static enemies

### ISSUE THREAD

**Issue by yuyin-W** [RinglingGameArt/2020_Soph_AdventureGame#45]
1. got weapon back to room 2
2. attack blocking enemies

problems: Sometimes I can't hurt the enemies, even if I stand in front of the enemy or very close to them.

expect: maybe change your character's attacking animation and the weapon collosion.

**Comment by ccorker** [comment]
Adjusted weapon; should take care of this issue. After several tests, issue appears resolved.
