### ISSUE TITLE
B1- Weapon not in hand B1- Weapon Hit Box

### ISSUE THREAD

**Issue by eabenoit01** [RinglingGameArt/2020_Soph_AdventureGame#47]
1) If you look closely your weapon inst in your characters hand which might cause some issues. I had this issue before! 
2) Also I think your weapon hit box should be a lot bigger. I have to get a lot closer to hit the enemies. 
3) Love the sound effects! 
![Screenshot (36)](https://user-images.githubusercontent.com/55291838/75993508-920c3d80-5ec7-11ea-896e-46b77579451c.png)

**Comment by ccorker** [comment]
-fixed weapon inst on Melee_BP
