### ISSUE TITLE
A1:  Room 9: The barrel is too long to hit the static enemy. And I think player needs something to hide.

### ISSUE THREAD

**Issue by yzhang210** [RinglingGameArt/2020_Soph_AdventureGame#50]
![UE4Game 2020-03-05 09-52-54-28](https://user-images.githubusercontent.com/55291906/75993375-60937200-5ec7-11ea-9aed-795746bafed9.jpg)

**Comment by ccorker** [comment]
-moved ranged enemies to corners of room; allows for more cover
-spaced out static enemies
