### ISSUE TITLE
C1: First Checkpoint, too much backtracking

### ISSUE THREAD

**Issue by apatters1** [RinglingGameArt/2020_Soph_AdventureGame#52]
If you die after the first checkpoint there's a lot of backtracking the player has to do. With how much damage the enemies do to the character + weapon functionality issues it gets frustrating to die and come back.

I would get rid of the first checkpoint, that way when the player respawns after getting that key they're back at the start of the game and don't have to go through 3 rooms to go to the left side of the level

**Comment by ccorker** [comment]
checkpoint moved to gate room
