### ISSUE TITLE
B1: Room 9- Difficulty of the room is too much with current Weapon Reach

### ISSUE THREAD

**Issue by AndresTVidal** [RinglingGameArt/2020_Soph_AdventureGame#53]
With how the weapon works right now, room 9 is too difficult since killing one ranged enemy will allow the other one to hit you, especially when it's so hard to hit enemies with the weapon range.

**Comment by ccorker** [comment]
-moved ranged enemies to corners of room 
-shortened barrel of turrets
-spaced out static enemies
