### ISSUE TITLE
A3; weapon static weapon collisions hard to hit

### ISSUE THREAD

**Issue by ewoods505** [RinglingGameArt/2020_Soph_AdventureGame#55]
This has been touched upon in class but I struggled getting passed some of the obstacles in the level. the player has to be extremely close to the static hazards to hit them. and even when I was right next to a static enemy (I forget the room but it was the second string of enemies blocking a door). I couldn't hit it.  Maybe a bigger collision on the weapon or the enemy will help.

**Comment by ccorker** [comment]
Adjusted weapon
