### ISSUE TITLE
B1: Room2: If you touch the wolf's nose, you won't be hurt, but if you turn your direction you will be hurt

### ISSUE THREAD

**Issue by yzhang210** [RinglingGameArt/2020_Soph_AdventureGame#8]
![UE4Game 2020-03-05 09-32-09-15](https://user-images.githubusercontent.com/55291906/75991355-5d4ab700-5ec4-11ea-8184-e414fdd59211.jpg)

**Comment by apatters1** [comment]
Changed collision on static enemy from box collision to mesh collision. Every part of enemy now does damage consistently, no weird 'slide' into damage due to nose being inactive
