### ISSUE TITLE
C2- Weapon and Enemy Hitboxes

### ISSUE THREAD

**Issue by AndresTVidal** [RinglingGameArt/2020_Soph_AdventureGame#813]
I'll swing with my weapon at the same location for a static enemy and one time it will work, the other times it won't. When a patrol enemy turns around, the hurt-box appears to be larger on the back-end of the patrol. The hitbox on the weapon seems fidgety at times as well but overall works well.

**Comment by apatters1** [comment]
Changed weapon collision to a hitbox in front of player, seems to have fixed all accuracy issues
