### ISSUE TITLE
S1-Hiding Moving Traps

### ISSUE THREAD

**Issue by AndresTVidal** [RinglingGameArt/2020_Soph_AdventureGame#818]
Currently, it's very hard to tell that the moving traps are there. Currently, the only indicator is the trigger area for the moving traps but it is difficult to spot. However, later on, if there's a possibility, a slight red glow or other light source to help the enemies pop more. For now, maybe push the top of the "cave" slightly back to reveal more of the enemy, maybe by 16-32 units back?

**Comment by apatters1** [comment]
Added glowy floor and pushed back top blocks of the 'caves'. Will definitely keep this feedback in mind going into polishing.
