### ISSUE TITLE
B2: Weapon can break when spammed

### ISSUE THREAD

**Issue by apatters1** [RinglingGameArt/2020_Soph_AdventureGame#820]
Weapon feels a lot better than before! But now I can spam it nonstop and it feels like it should do damage constantly, but I have to wait for the 'spammed' hits to stop, then the hit will register.

Maybe add a delay before the input resets so the player can't spam it constantly plus it could add some risk/reward to timing attacks :)

**Comment by sbeauchaa** [comment]
Completely changed the way that the weapon works. The player now gets stopped properly while using the weapon and there is a delay so that spamming the weapon does not spam the animation.
