### ISSUE TITLE
B2: Ranged enemies hard to hit, no build up sounds/visuals

### ISSUE THREAD

**Issue by apatters1** [RinglingGameArt/2020_Soph_AdventureGame#821]
It doesn't feel like I can get close enough to damage the ranged enemy in time before it's charged and firing again and there's no warning for when it will fire. And when it looks like I should be close enough to damage it, nothing happens.

**Comment by sbeauchaa** [comment]
Worked on adding visual and audio cues for the ranged enemies and their attacks, also changed the collision box the enemy so that it better fit them.
