### ISSUE TITLE
A4- Movement and Attacking Are Inconsistent From Room to Room

### ISSUE THREAD

**Issue by AndresTVidal** [RinglingGameArt/2020_Soph_AdventureGame#869]
In some rooms, if you attack, you can't move which how it's meant to be. However, in other rooms, you can walk and attack at the same time but in the next room in reverts to the other method. Hard to replicate but very weird to play.

**Comment by sbeauchaa** [comment]
Fixed that by changed the movement blueprint that was related to an issue with the weapon. Mentioned in a different issue.
