### ISSUE TITLE
B4: Walking Sound Effect repeats Forever upon death

### ISSUE THREAD

**Issue by AndresTVidal** [RinglingGameArt/2020_Soph_AdventureGame#9]
Hard to reproduce but while walking into an enemy while dying, upon respawn, walking sound effect repeats. Not critical but makes playing the game a bit more annoying.

**Comment by apatters1** [comment]
Fixed by changing Spawn Sound 2D to an audio component tied to the character. Sound no longer repeats upon death or continuously upon respawn
