### ISSUE TITLE
B1- Health Bar isn't 100% Accurate

### ISSUE THREAD

**Issue by AndresTVidal** [RinglingGameArt/2020_Soph_AdventureGame#984]
When you take the first hit (from 100% to 90%) the health bar doesn't reflect this. Maybe it's an issue with the mask? Is it the right size in Photoshop or wherever it was made? Either way, it's noticeable and leaves players confused when they first get hit.

**Comment by sbeauchaa** [comment]
Fix the health bar, the margin in the margin was too large and it was trying to draw the missing health in hidden space instead of the visible space. Made the margin the correct size so that it shows the hit.
