### ISSUE TITLE
B2- Knockback leads to combos in some Rooms

### ISSUE THREAD

**Issue by AndresTVidal** [RinglingGameArt/2020_Soph_AdventureGame#990]
The knockback is hefty and works most of the time, but maybe decreasing by 5-10% might help it feel a bit better, plus it would fit more with the theme of things being heavy. My main suggestion would be delay when the enemies can hit you again to create some invincibility frames. Maybe dealy it by .6 or 1 seconds to make it less likely to be combo'd infinitely.

**Comment by sbeauchaa** [comment]
Changed the enemy placement for the room that it was creating a terrible combo in. Decreased the knockback as well by 5%. Also added a .5 delay for the hits of the static enemies.
